version: '3'

volumes:
  cache:
    driver: local
services:
  cache:
    image: redis:7.2.3-alpine3.18
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning
    volumes: 
      - cache:/data
  ui:
    entrypoint: ["npm", "start"]
    environment:
      NODE_ENV: development
    image: node:20-alpine3.18
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/opt/ui
    working_dir: /opt/ui

  server:
    entrypoint: ["npm", "run","watch"]
    depends_on:
      - cache
    environment:
      NODE_ENV: development
    image: node:20-alpine3.18
    links:
      - database:database
      - cache:cache
    ports:
      - "8080:8080"
    volumes:
      - ./server:/opt/server
    working_dir: /opt/server
  


  database:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: hipages
      MYSQL_DATABASE: hipages
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d